name: make n2_z81c 050

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      arch:
        description: 'Select box type'
        type: choice
        required: true
        default: 'z81c_box'
        options:
          - z81c_box
          - n2_box
jobs:
  build-z81c:
    if: ${{inputs.arch == 'z81c_box'}}
    runs-on: ubuntu-22.04
    name: 编译z81c
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: 安装编译依赖和环境
        id: init
        run: |
          sudo -E apt-get -y update
          sudo -E apt-get -y install gcc make gettext bison flex bc zlib1g-dev libncurses5-dev lzma git
          sudo mkdir -p /builder
          sudo chown -R runner.runner /builder
          echo "status=success" >> ${GITHUB_OUTPUT}

      - name: 克隆sdk
        id: clone
        working-directory: /builder
        if: ${{ steps.init.outputs.status }} == 'success' && !cancelled()
        run: |
          git clone -q --single-branch --depth=1 https://github.com/JasonFreeLab/HiSTBLinuxV100R005C00SPC050 mv200
          cd mv200
          cp ${GITHUB_WORKSPACE}/configs/hi3798mv2dmf_hi3798mv200-64.mak ./cfg.mak
          cp ${GITHUB_WORKSPACE}/config_files/hi3798mv200_defconfig-64 mv200/source/kernel/linux-4.4.y/arch/arm64/configs/hi3798mv200_defconfig
          cp ${GITHUB_WORKSPACE}/config_files/hi3798mv2dmf_hi3798mv200_DDR3-1866_2GB_8bitx4_4layers.reg mv200/source/boot/sysreg/hi3798mv200    
          echo "status=success" >> ${GITHUB_OUTPUT}

      - name: 编译sdk
        id: build
        working-directory: /builder
        if: ${{ steps.clone.outputs.status }} == 'success' && !cancelled()
        run: |
          cd mv200
          source ./env.sh
          make hiboot
          make linux -j4 2>&1  | tee -a buildlog.txt
          mkdir /builder/kmod
          mkdir /builder/out
          cp /builder/mv200/out/hi3798mv200/hi3798mv2dmf/image/emmc_image/fastboot.bin /builder/out/fastboot_z81c.bin
          cp /builder/mv200/out/hi3798mv200/hi3798mv2dmf/image/emmc_image/hi_kernel.bin /builder/out/hi_kernel-z81c.bin
          cd /builder/mv200/out/hi3798mv200/hi3798mv2dmf/obj/source/kernel/linux-4.4.y
          cp modules.order 123.txt
          sed -i "s/kernel\///" 123.txt
          cp --parents $(cat 123.txt) /builder/kmod/
          tar -zcvf /builder/out/z81c_kmod.tar.gz /builder/kmod/*
          echo "status=success" >> ${GITHUB_OUTPUT}

      - name: 上传编译结果
        id: tar
        uses: ncipollo/release-action@main
        if: ${{ steps.build.outputs.status }} == 'success' && !cancelled()
        with:
          tag: mv200_kernel
          artifacts: /builder/out
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            - 海思3798mv200内核，适用于Z81c。

  build-n2:
    if: ${{inputs.arch == 'n2_box'}}
    name: 编译N2
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: 安装编译依赖和环境
        id: init
        run: |
          sudo -E apt-get -y update
          sudo -E apt-get -y install gcc make gettext bison flex bc zlib1g-dev libncurses5-dev lzma git
          sudo mkdir -p /builder
          sudo chown -R runner.runner /builder
          echo "status=success" >> ${GITHUB_OUTPUT}

      - name: 克隆sdk
        id: clone
        working-directory: /builder
        if: ${{ steps.init.outputs.status }} == 'success' && !cancelled()
        run: |
          git clone -q --single-branch --depth=1 https://github.com/JasonFreeLab/HiSTBLinuxV100R005C00SPC050 mv200
          cd mv200
          cp ${GITHUB_WORKSPACE}/configs/hi3798mv2dmc_n2_cfg.mak ./cfg.mak
          cp ${GITHUB_WORKSPACE}/config_files/hi3798mv200_n2_defconfig mv200/source/kernel/linux-4.4.y/arch/arm64/configs/hi3798mv200_defconfig
          cp ${GITHUB_WORKSPACE}/config_files/hi3798mv2dmc_hi3798mv200_DDR4-2133_2GB_16bitx2_4layers_n2ns1_wtt.reg mv200/source/boot/sysreg/hi3798mv200
          echo "status=success" >> ${GITHUB_OUTPUT}

      - name: 编译sdk
        id: build
        working-directory: /builder
        if: ${{ steps.clone.outputs.status }} == 'success' && !cancelled()
        run: |
          cd mv2000
          source ./env.sh
          make hiboot
          make linux -j4 2>&1  | tee -a buildlog.txt
          mkdir /builder/kmod
          mkdir /builder/out
          cp /builder/mv200/out/hi3798mv200/hi3798mv2dmc/image/emmc_image/fastboot.bin /builder/out/fastboot_n2.bin
          cp /builder/mv200/out/hi3798mv200/hi3798mv2dmc/image/emmc_image/hi_kernel.bin /builder/out/hi_kernel_n2.bin
          cd /builder/mv200/out/hi3798mv200/hi3798mv2dmc/obj64/source/kernel/linux-4.4.y
          cp modules.order 123.txt
          sed -i "s/kernel\///" 123.txt
          cp --parents $(cat 123.txt) /builder/kmod/
          tar -zcvf /builder/out/n2_kmod.tar.gz /builder/kmod/*
          echo "status=success" >> ${GITHUB_OUTPUT}

      - name: 上传编译结果
        id: tar
        uses: ncipollo/release-action@main
        if: ${{ steps.build.outputs.status }} == 'success' && !cancelled()
        with:
          tag: mv200_kernel
          artifacts: /builder/out
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            - 海思3798mv200内核，适用于N2。
