name: make mv300 060

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      set_chip_type:
        description: "Select Chip Type."
        required: false
        default: "hi3798mv300dmw"
        type: choice
        options:
          - hi3798mv2dma
          - hi3798mv300dmw
      set_arch_type:
        description: "Select arch type."
        required: false
        default: "arm64"
        type: choice
        options:
          - arm
          - arm64
jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Initialization environment
        id: init
        run: |
          sudo -E apt-get -y update
          sudo -E apt-get -y install gcc make gettext zlib1g-dev libncurses5-dev bison flex bc texinfo tree cmake flex lzma git
          sudo mkdir -p /builder
          sudo chown -R runner.runner /builder
          echo "status=success" >> ${GITHUB_OUTPUT}
          
      - name: make build
        id: build
        working-directory: /builder
        if: ${{ steps.init.outputs.status }} == 'success' && !cancelled()
        run: |
          git clone -q --single-branch --depth=1 https://github.com/JasonFreeLab/HiSTBLinuxV100R005C00SPC060 mv300
          cd mv300
          source ./env.sh
          make hiboot
          cp /builder/mv300/out/hi3798mv300/${{ inputs.set_chip_type }}/image/emmc_image/fastboot.bin /builder/fastboot_${{ inputs.set_chip_type }}.bin
          #make linux -j2 2>&1  | tee -a buildlog.txt
          echo "status=success" >> ${GITHUB_OUTPUT}
          
      - name: Upload Kernel to Release
        id: tar
        uses: ncipollo/release-action@v1
        if: ${{ steps.build.outputs.status }} == 'success' && !cancelled()
        with:
          tag: mv300_kernel_060
          artifacts: /builder/fastboot_${{ inputs.set_chip_type }}.bin,/builder/mv300/out/hi3798mv300/${{ inputs.set_chip_type }}/image/emmc_image/hi_kernel.bin
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            - 海思3798Mv300内核 32位。
